### PR TITLE
feat: v4.3

### PR DESCRIPTION
**Pull request by justchokingaround**

### CODE REVIEW

**Comment by justchokingaround** [comment]
TODO:
- [ ] shellcheck
- [ ] other OSs compatibility

**Comment by justchokingaround** [comment]
closes #126

**Comment by justchokingaround** [comment]
What's new:

* [DEPRECATED] history option in the config file is dropped => now if you use mpv's save-on-quit feature it will automatically save your position to history otherwise it won't (the default bind for this is shift+q, you can also specify save-on-quit in your mpv configuration so that it is always used by default) (requires: awk)
* [NEW FEATURE] native shell implementation of discord rich presence (only supported on UNIX systems, for now untested on macOS) (requires: BSD netcat)
* [NEW FEATURE] use fzf's default chafa image preview by default, ueberzugpp now becomes optional (but you can still use it if you had it configured before by adding `use_ueberzug=true` to your config)
* [CRITICAL CHANGE] the config file is now named `lobster_config.sh` instead of `lobster_config.txt`
* [CRITICAL_CHANGE] any config option that used 0/1 before now uses false/true strings respectively
* [BUGFIXES] i don't remember lol, just check the closes comment

**Comment by ttx99** [comment]
how to try this?

**Comment by justchokingaround** [comment]
```sh
git clone https://github.com/justchokingaround/lobster
cd lobster/
sh lobster.sh --help
```

**Comment by ttx99** [comment]
> [NEW FEATURE] use fzf's default chafa image preview by default, ueberzugpp now becomes optional (but you can still use it if you had it configured before by adding use_ueberzugpp=true to your config.

Supposed to windows or no?

**Comment by justchokingaround** [comment]
no

**Pull request merged**
