### PR TITLE
add the provider setting; allowing to choose multiple sources

### PR DESCRIPTION
**Pull request by Nooguat**
First, thanks for this script; so useful on everyday basis. 
I tried to add multiple sources checking as sometime lobster can't find link (issue https://github.com/justchokingaround/lobster/issues/14). This is controlled by a key in the config file (`providers`) with the sources separated by comma. 
Hope you will find it usefulm 
Regards

### CODE REVIEW

**Comment by justchokingaround** [comment]
i really appreciate the effort, however these changes didn't even work for me, and there is a lot of bashism in ur version, so i will not merge yet
image
if u have any questions or don't understand something, u can always ask me, i'll always help

**Comment by Nooguat** [comment]
Hi, 
Thanks for your response. 
Totally understand that you don't want to merge ; I'm still training my bash skills (I hope that if you find the time, you could point to the messy things I did).
About the crash you encountered I think I found the issue. At first I did not have it on my end (did you set only one provider ?) 
I tried to patch it ; now working for me but got issue with any other provider than Vidcloud. I will continue to investigate on it, but if you have any clue I'm interested.

**Comment by justchokingaround** [comment]
ok so first of all it's important that you understand the difference between bash and posix shell. in this case the script is not a bash script, it's a posix shell script (you can tell from the shebang #!/bin/sh). bashisms are things that will only work with bash but not necessarily other posix compliant shells (zsh, dash...). an example could be the use of double brackets [[ foo ]]. to make sure the script is posix compliant, you can use shellcheck (if you use vim/nvim you can set up a keybind to run the shellcheck command on the current file). as for the video links' encryption i'll deal with it myself so you don't have to worry about the encryption part just yet. i'll answer any other questions you have. i'll do a more thorough code review later, but i already saw a few bashisms (avoid using while loops and i recommend you watch luke smith's video on if and else statements)

**Comment by Nooguat** [comment]
Hi, 
Thanks for the precision about POSIX and the luke smith video. 
According to `shellcheck` the script is POSIX friendly. 
Encountered the same issue as  https://github.com/justchokingaround/lobster/issues/19 ; seems the `mpv_link` variable now contains vtt file. 
If I do anything to help please do reach me ; still got plenty of time for some days.
Regards

**Comment by justchokingaround** [comment]
thanks. the .vtt file is for subtitles, the video links end in .m3u8 but there's one (or more) providers that encrypt it now, i'll fix that

**Comment by justchokingaround** [comment]
closing in favor of 32841b4d710a5e6d85ecbe3ccb699e8ddb9e97be
ty for ur hardwork, i appreciate it but i've had to do a pretty big refactor which makes this pr obsolete

**Pull request closed without merging**
